In [1]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

In [2]:
engine = create_engine("mysql+pymysql://root:your_password@localhost/superstore_db")

-- ----------------------------------------------------------------
-- 1. VERIFY DATA IMPORT INTEGRITY
-- ----------------------------------------------------------------

In [3]:
pd.read_sql("""SELECT 
                COUNT(*) AS total_rows,
                COUNT(DISTINCT `Order ID`) AS total_orders,
                COUNT(DISTINCT `Customer ID`) AS total_customers,
                ROUND(SUM(Sales), 2) AS total_gross_sales,
                ROUND(SUM(Profit), 2) AS total_net_profit,
                ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS overall_profit_margin_pct
            FROM retail_orders;""",engine)

,total_rows,total_orders,total_customers,total_gross_sales,total_net_profit,overall_profit_margin_pct
0,9994,5009,793,2297200.86,286397.02,12.47

-- ----------------------------------------------------------------
-- 2. IDENTIFY LOSS-LEADERS (Sub-Categories Destroying Margins)
-- SQL Concept: GROUP BY, HAVING, ORDER BY
-- Business Value: Pinpoints lines operating at an aggregate net loss.
-- ----------------------------------------------------------------

In [4]:
pd.read_sql("""SELECT 
    `Sub-Category`,
    COUNT(`Order ID`) AS items_sold,
    ROUND(SUM(Sales), 2) AS total_sales,
    ROUND(SUM(Profit), 2) AS net_profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS profit_margin_pct
FROM retail_orders
GROUP BY `Sub-Category`
HAVING net_profit < 0
ORDER BY net_profit ASC;""",engine)

  Sub-Category  items_sold  total_sales  net_profit  profit_margin_pct
0       Tables         319    206965.53   -17725.48              -8.56
1    Bookcases         228    114880.00    -3472.56              -3.02
2     Supplies         190     46673.54    -1189.10              -2.55

-- ----------------------------------------------------------------
-- 3. THE DISCOUNT MARGIN EROSION ANALYSIS
-- SQL Concept: CASE WHEN, Aggregate Profit Margin calculation
-- Business Value: Evaluates how margin drops as discount brackets rise.
-- ----------------------------------------------------------------

In [21]:
pd.read_sql("""
    SELECT 
        CASE 
            WHEN Discount = 0 THEN '0%% (No Discount)'
            WHEN Discount <= 0.20 THEN '1%% - 20%%'
            WHEN Discount <= 0.40 THEN '21%% - 40%%'
            WHEN Discount <= 0.60 THEN '41%% - 60%%'
            ELSE '61%%+'
        END AS discount_tier,
        COUNT(DISTINCT `Order ID`) AS total_orders,
        ROUND(SUM(Sales), 2) AS total_sales,
        ROUND(SUM(Profit), 2) AS total_profit,
        ROUND((SUM(Profit) / NULLIF(SUM(Sales), 0)) * 100, 2)
            AS aggregate_margin_pct
    FROM retail_orders
    GROUP BY discount_tier
    ORDER BY total_profit DESC;
""", engine)

,discount_tier,total_orders,total_sales,total_profit,aggregate_margin_pct
0,0% (No Discount),2644,1087908.47,320987.60,29.51
1,1% - 20%,2507,846522.24,100785.47,11.91
2,41% - 60%,195,71048.21,-28944.19,-40.74
3,21% - 40%,400,234137.90,-35817.47,-15.30
4,61%+,594,57584.04,-70614.40,-122.63

-- ----------------------------------------------------------------
-- 4. MONTHLY REVENUE & CUMULATIVE RUNNING TOTAL
-- SQL Concept: Common Table Expressions (CTE), Window Function (SUM() OVER)
-- Business Value: Shows growth momentum and cumulative sales progression.
-- ----------------------------------------------------------------

In [6]:
pd.read_sql("""
WITH MonthlySummary AS (
    SELECT 
        `Order Month` AS order_month,
        ROUND(SUM(Sales), 2) AS monthly_sales,
        ROUND(SUM(Profit), 2) AS monthly_profit
    FROM retail_orders
    GROUP BY `Order Month`
)
SELECT 
    order_month,
    monthly_sales,
    monthly_profit,
    ROUND(SUM(monthly_sales) OVER (ORDER BY order_month), 2) AS cumulative_running_sales
FROM MonthlySummary
ORDER BY order_month ASC;
""", engine)

   order_month  monthly_sales  monthly_profit  cumulative_running_sales
0      2014-01       14236.89         2450.19                  14236.89
1      2014-02        4519.89          862.31                  18756.78
2      2014-03       55691.01          498.73                  74447.79
3      2014-04       28295.34         3488.84                 102743.13
4      2014-05       23648.29         2738.71                 126391.42
5      2014-06       34595.13         4976.52                 160986.55
6      2014-07       33946.39         -841.48                 194932.94
7      2014-08       27909.47         5318.10                 222842.41
8      2014-09       81777.35         8328.10                 304619.76
9      2014-10       31453.39         3448.26                 336073.15
10     2014-11       78628.72         9292.13                 414701.87
11     2014-12       69545.62         8983.57                 484247.49
12     2015-01       18174.08        -3281.01                 502421.57
13     2015-02       11951.41         2813.85                 514372.98
14     2015-03       38726.25         9732.10                 553099.23
15     2015-04       34195.21         4187.50                 587294.44
16     2015-05       30131.69         4667.87                 617426.13
17     2015-06       24797.29         3335.56                 642223.42
18     2015-07       28765.32         3288.65                 670988.74
19     2015-08       36898.33         5355.81                 707887.07
20     2015-09       64595.92         8209.16                 772482.99
21     2015-10       31404.92         2817.37                 803887.91
22     2015-11       75972.56        12474.79                 879860.47
23     2015-12       74919.52         8016.97                 954779.99
24     2016-01       18542.49         2824.82                 973322.48
25     2016-02       22978.82         5004.58                 996301.30
26     2016-03       51715.88         3611.97                1048017.18
27     2016-04       38750.04         2977.81                1086767.22
28     2016-05       56987.73         8662.15                1143754.95
29     2016-06       40344.53         4750.38                1184099.48
30     2016-07       39261.96         4432.88                1223361.44
31     2016-08       31115.37         2062.07                1254476.81
32     2016-09       73410.02         9328.66                1327886.83
33     2016-10       59687.75        16243.14                1387574.58
34     2016-11       79411.97         4011.41                1466986.55
35     2016-12       96999.04        17885.31                1563985.59
36     2017-01       43971.37         7140.44                1607956.96
37     2017-02       20301.13         1613.87                1628258.09
38     2017-03       58872.35        14751.89                1687130.44
39     2017-04       36521.54          933.29                1723651.98
40     2017-05       44261.11         6342.58                1767913.09
41     2017-06       52981.73         8223.34                1820894.82
42     2017-07       45264.42         6952.62                1866159.24
43     2017-08       63120.89         9040.96                1929280.13
44     2017-09       87866.65        10991.56                2017146.78
45     2017-10       77776.92         9275.28                2094923.70
46     2017-11      118447.83         9690.10                2213371.53
47     2017-12       83829.32         8483.35                2297200.85

-- ----------------------------------------------------------------
-- 5. TOP 3 CUSTOMERS PER REGION (RANKING)
-- SQL Concept: CTE, Window Function (DENSE_RANK() OVER PARTITION BY)
-- Business Value: Identifies VIP accounts in each geographic territory.
-- ----------------------------------------------------------------

In [7]:
pd.read_sql("""WITH RegionalCustomerSpend AS (
    SELECT 
        Region,
        `Customer Name`,
        ROUND(SUM(Sales), 2) AS total_spend,
        DENSE_RANK() OVER (
            PARTITION BY Region 
            ORDER BY SUM(Sales) DESC
        ) AS spending_rank
    FROM retail_orders
    GROUP BY Region, `Customer Name`
)
SELECT 
    Region,
    spending_rank,
    `Customer Name`,
    total_spend
FROM RegionalCustomerSpend
WHERE spending_rank <= 3
ORDER BY Region, spending_rank;
""",engine)

     Region  spending_rank   Customer Name  total_spend
0   Central              1    Tamara Chand     18437.14
1   Central              2   Adrian Barton     12181.59
2   Central              3    Becky Martin     10539.90
3      East              1    Tom Ashbrook     13723.50
4      East              2    Hunter Lopez     10522.55
5      East              3    Bill Shonely     10022.29
6     South              1     Sean Miller     23669.20
7     South              2    Sanjit Engle      8805.04
8     South              3  Grant Thornton      8167.42
9      West              1    Raymond Buch     14345.28
10     West              2    Ken Lonsdale      8472.39
11     West              3    Edward Hooks      7447.77

-- ----------------------------------------------------------------
-- 6. RFM SEGMENT REVENUE CONTRIBUTION & REVENUE SHARE
-- SQL Concept: Window Function for calculating % of Total inside SQL
-- Business Value: Validates customer concentration (e.g. Champions revenue %).
-- ----------------------------------------------------------------

In [8]:
pd.read_sql("""SELECT 
    `RFM Segment`,
    COUNT(DISTINCT `Customer ID`) AS total_customers,
    ROUND(SUM(Sales), 2) AS segment_revenue,
    ROUND(
        (SUM(Sales) / SUM(SUM(Sales)) OVER ()) * 100, 
        2
    ) AS revenue_share_pct
FROM retail_orders
GROUP BY `RFM Segment`
ORDER BY segment_revenue DESC;
""",engine)

       RFM Segment  total_customers  segment_revenue  revenue_share_pct
0        Champions              176        802935.47              34.95
1          At Risk              107        530689.63              23.10
2        Promising              159        357340.16              15.56
3  Needs Attention              110        325597.70              14.17
4      Hibernating              179        181741.61               7.91
5   Loyal / Active               62         98896.29               4.31

-- ----------------------------------------------------------------
-- 7. SHIPPING DURATION PERFORMANCE & SLA BREACH (> 4 DAYS)
-- SQL Concept: Conditional Aggregation (SUM(CASE WHEN ...))
-- Business Value: Analyzes fulfillment speed and delivery reliability.
-- ----------------------------------------------------------------

In [9]:
pd.read_sql("""SELECT 
    `Ship Mode`,
    COUNT(`Order ID`) AS total_shipments,
    ROUND(AVG(`Shipping Days`), 1) AS avg_shipping_days,
    SUM(CASE WHEN `Shipping Days` > 4 THEN 1 ELSE 0 END) AS delayed_orders,
    ROUND(
        (SUM(CASE WHEN `Shipping Days` > 4 THEN 1 ELSE 0 END) / COUNT(`Order ID`)) * 100, 
        2
    ) AS delay_rate_pct
FROM retail_orders
GROUP BY `Ship Mode`
ORDER BY avg_shipping_days ASC;
""",engine)

,Ship Mode,total_shipments,avg_shipping_days,delayed_orders,delay_rate_pct
0,Same Day,543,0.0,0.0,0.00
1,First Class,1538,2.2,0.0,0.00
2,Second Class,1945,3.2,429.0,22.06
3,Standard Class,5968,5.0,3564.0,59.72